---
kind: pipeline
type: docker
name: default

steps:
- name: validate and plan
  image: hashicorp/terraform
  environment:
    TOKEN:
      from_secret: TOKEN
    TF_CLI_CONFIG_FILE:
      from_secret: TF_CLI_CONFIG_FILE
  commands:
  - chmod +x creds.sh
  - ./creds.sh
  - cat ./credentials
  - terraform init
  - terraform plan
trigger: 
  branch:
    - master
  event:
    - push
